"""add language to reviews

Revision ID: 355b9996f3f2
Revises: a315b0093bf5
Create Date: 2026-08-16 23:20:57.000242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '355b9996f3f2'
down_revision: Union[str, Sequence[str], None] = 'a315b0093bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'reviews',
        sa.Column(
            'language',
            sa.String(length=50),
            nullable=False,
            server_default='python'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'language')
    # ### end Alembic commands ###
