"""add ai review to reviews

Revision ID: 93abf841f353
Revises: 53245ca698e9
Create Date: 2026-08-17 21:39:34.262742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93abf841f353'
down_revision: Union[str, Sequence[str], None] = '53245ca698e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('ai_review', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'ai_review')
    # ### end Alembic commands ###
